Use LichHopCongTac
DECLARE @INSTR as VARCHAR(MAX)
SET @INSTR = '14,15,16,'
DECLARE @SEPERATOR as VARCHAR(1)
DECLARE @SP INT
DECLARE @VALUE VARCHAR(1000)

DECLARE @Txt NVARCHAR(MAX)
SET @Txt = ''

SET @SEPERATOR = ','
CREATE TABLE #tempTab (id int not null)
WHILE PATINDEX('%' + @SEPERATOR + '%', @INSTR ) <> 0 
BEGIN
   SELECT  @SP = PATINDEX('%' + @SEPERATOR + '%',@INSTR)
   SELECT  @VALUE = LEFT(@INSTR , @SP - 1)
   SELECT  @INSTR = STUFF(@INSTR, 1, @SP, '')
   
   IF @Txt!=''
        SET @Txt=@Txt+', ' + (SELECT TenDayDu FROM DmPhongDoiCC WHERE ID=@VALUE)
    ELSE
        SET @Txt=(SELECT TenDayDu FROM DmPhongDoiCC WHERE Id=@VALUE)
        
   
   INSERT INTO #tempTab (id) VALUES (@VALUE)
   
END

SELECT @Txt AS Txt

SELECT * FROM DmPhongDoiCC WHERE id IN (SELECT id FROM #tempTab)
DROP TABLE #tempTab